image: registry.gitlab.com/canya-com/devops/smart-contract-build-container:0.1

variables:
  APP_PATH: /builds/$CI_PROJECT_PATH

before_script:
  - cd $APP_PATH
  - npm install
  - ganache-cli -p 8545 > /dev/null &
  - sleep 5

stages:
  - validate

lint:solium:
  stage: validate
  script:
    - cd $APP_PATH
    - echo -n "+ current working path:" && pwd
    - npm run lint

test:truffle:
  stage: validate
  script:
    - cd $APP_PATH
    - npm run test
