image: node:8.14.0-jessie

variables:
  APP_PATH: /builds/$CI_PROJECT_PATH

before_script:
  - npm install -g ganache-cli
  - cd $APP_PATH
  - npm install
  - ganache-cli -p 8545 > /dev/null &
  - sleep 5

stages:
  - validate

lint:solium:
  stage: validate
  script:
    - cd $APP_PATH
    - echo -n "+ current working path:" && pwd
    - npm run lint

test:truffle:
  stage: validate
  script:
    - cd $APP_PATH
    - npm run test
