image: registry.gitlab.com/canya-com/node-build-container:1.2

variables:
  APP_PATH: /builds/$CI_PROJECT_PATH

stages:
  - test

truffle:
  stage: test
  script:
    - npm install -g solium
    - cd $APP_PATH
    - echo -n "+ current working path:" && pwd
    - solium -d ./contracts

solium:
  stage: test
  script:
    - npm install -g truffle@5.0.0-beta.2
    - cd $APP_PATH
    - echo -n "+ current working path:" && pwd
    - truffle test