image: registry.gitlab.com/canya-com/node-build-container:1.2

variables:
  APP_PATH: /builds/$CI_PROJECT_PATH

before_script:
  - npm install

stages:
  - test

truffle:
  stage: test
  script:
    - cd $APP_PATH
    - echo -n "+ current working path:" && pwd
    - npm run lint

solium:
  stage: test
  script:
    - cd $APP_PATH
    - echo -n "+ current working path:" && pwd
    - npm run test